### ISSUE TITLE
"Find Me" doesn't work

### ISSUE THREAD

**Issue by javery86** [hypeJunction/hypeWall#100]
Whenever I click on the "Find Me" link to autopopulate my location, nothing seems to happen. Also, when I inspected it via Google Chrome Console, I see these errors:

jquery.js:2 Uncaught Error: Syntax error, unrecognized expression: #
at Function.fa.error (jquery.js:2)
at fa.tokenize (jquery.js:2)
at Function.fa [as find] (jquery.js:2)
at n.fn.init.find (jquery.js:2)
at HTMLAnchorElement. (tabs.js:3)
at HTMLDocument.dispatch (jquery.js:2)
at HTMLDocument.r.handle (jquery.js:2)
fa.error @ jquery.js:2
fa.tokenize @ jquery.js:2
fa @ jquery.js:2
find @ jquery.js:2
(anonymous) @ tabs.js:3
dispatch @ jquery.js:2
r.handle @ jquery.js:2

**Comment by hypeJunction** [comment]
Some other script is throwing error. What's tabs.js?

**Comment by javery86** [comment]
I have no idea.

**Comment by hypeJunction** [comment]
Me neither.

**Comment by javery86** [comment]
Well, it's actually a dependency for hypeInvite which is something I wanted to use too.

**Comment by hypeJunction** [comment]
Open an issue there. I will get to it some day.

**Comment by javery86** [comment]
Sure thing.
