### ISSUE TITLE
Photo shareing tab

### ISSUE THREAD

**Issue by wanderingbear1** [hypeJunction/hypeWall#27]
The link in the photo share tab doesn’t work right. when I click on the link to upload a photo.Nothing happens.

**Comment by propertunist** [comment]
i am seeing the same issue here with elgg 2.1 and the latest release of hypewall

**Comment by propertunist** [comment]
anyone got hypewall to correctly render images? i am unable to use the plugin until this is resolved and this is an old ticket. i looked through the hypewall river object code and see no mention of any support for images at all.
