### ISSUE TITLE
When comment icon is clicked in Wall widget, comment form opens in Activity widget

### ISSUE THREAD

**Issue by dranii** [hypeJunction/hypeWall#48]
Elgg 1.9.6 - fresh install, no other plugins, then hypewall (and hypefilestore) and Widget Manager
Log in as admin ( can login as another user also) 
On User Profile page -> Add widgets -> Add Activity and Hypewall Widget
When comment icon is clicked in Wall widget, comment form opens in Activity widget
Expected : Comment form to open in Wall widget only

Problem of Widget Manager? Hypewall? Both?
![wal-acy-cmnt](https://cloud.githubusercontent.com/assets/9887635/5254292/38fd6322-79d5-11e4-8d7b-38741e261c9b.PNG)

**Comment by hypeJunction** [comment]
Closing as won't fix. I have done my share of work with comments in hypeInteractions.
