### ISSUE TITLE
 "with username" appending in wall message is suddenly missing

### ISSUE THREAD

**Issue by dranii** [hypeJunction/hypeWall#49]
Okay, this one leaves me totally confused and frustrated.
While testing with the community downloadable version  / github master version I got the tagging feature of hypewall *apparently* working - that is, if a status message was posted in the format " abcxyz @username" the username got hyperlinked as well as "with username" was appended - see picture
![hypwl1](https://cloud.githubusercontent.com/assets/9887635/5271949/607aaa94-7a9e-11e4-8818-c2ec01b379f2.PNG)

After testing with the dev version that corrected the issue #47 I am no longer getting the above feature. To test from scratch again, I made a fresh install of Elgg 1.9.4 and Friend Request and hypewall (with hypefilestore) - I have set all user settings as admin as well as test users' settings okay - but still not getting the tagging feature. What am I missing? Any other hype plugin needed?

Same result with 1.96 Elgg, and dev and master versions of hypewall. Can anyone please test?

**Comment by hypeJunction** [comment]
Can't reproduce now.
