### ISSUE TITLE
FR :  I do not have to leave my page to send a status to a friend

### ISSUE THREAD

**Issue by rhisss** [hypeJunction/hypeWall#52]
When Wire form is used I can post a message to @myfriend in my own profile page using the form and the message gets sent to the @myfriend's profile/wire. Thus I do not have to leave my page to send a status to a friend. However, when hypeWall  Wall form is used this does not happen. One has to go to that 'myfriend's profile/wire to send message. 

Can this behavior of the Wire be incorporated into the 1.9.x version / 1.10 version of HypeWall.
Additionally when Mentions is enabled @names do not get transformed to profile hyperlinks in Hypewall but they do get so in other entities.

**Comment by hypeJunction** [comment]
Each friend you tag, receives a river item. Wall is displayed using river feed, so I don't see a problem here. For hyperlinking, use hypeScraper, or wrap the output in ```output/longtext``` view.
