### ISSUE TITLE
Wall messages cannot be seen in Wall widget in user profile page

### ISSUE THREAD

**Issue by rhisss** [hypeJunction/hypeWall#53]
When Wire is used to 'select the model for the wall posts' the status messages show in the widget but once the page is refreshed they are not there. In other words if Wire functionality is used for Wall messages the Wall messages cannot be seen , for example, in the Wall widget in user profile page.

This happens on fresh installl of Elgg 1.9.6, no other plugins, and all versions of hypewall - 1.9. master, dev
Additionally at someone messages are not automatically going to that at someone's wall - also Mentions is not working in Wall (though it works everywhere else)

**Comment by hypeJunction** [comment]
I think this has been resolved. Can't replicate now.
