### ISSUE TITLE
@username does not get formatted to user profile link

### ISSUE THREAD

**Issue by dranii** [hypeJunction/hypeWall#54]
Using the Mentions plugin, it is possible that @username is converted to hyperlinks in blog, comments and other entities. But within the Wall it is not happening. In Wall Widget in profile page or the Wall page at names remain at names. I have tried with vanilla Elgg 1.9.6 and master and dev versions of Hypewall.

**Comment by hypeJunction** [comment]
Output ```$entity->description``` through ```elgg_view('output/longtext')``` in ```object/hjwall/elements/message```. Not going to support that out of the box.
