### ISSUE TITLE
Shared photos to go into a default album created for each user when the first photo is shared

### ISSUE THREAD

**Issue by isoguci1** [hypeJunction/hypeWall#55]
Currently the photos saved as photos. This creates some discrepancy, as usually photos are organized into (Tidypics) albums. So when you look at a user's photo's, the ones shared via hypeWall are missing there. 

I believe the following behaviour would be more consistent across elgg:
- When user shares a photo via hypeWall, it is saved in the default (or "generic") album of the user. The first time a user shares a photo via hypeWall, the default album is automatically created. As for albums, I mean the tidypics albums. And they are per user (as opposed to site-wide).
regards.

**Comment by isoguci1** [comment]
CORRECTİON: "Currently the photos saved as photos" should read as: "Currently the photos saved as FILES".

**Comment by hypeJunction** [comment]
Dupe of #18
