### ISSUE TITLE
Geolocation not working

### ISSUE THREAD

**Issue by Crowbar90** [hypeJunction/hypeWall#56]
In the submit post form, when I click on “Find me” to get my location, nothing happens. I don’t think it’s a permission issue because my browser asks me to use my location, but I just see an empty box instead of the location.
![hypewall](https://cloud.githubusercontent.com/assets/1532866/5916821/d29b7f48-a615-11e4-8bea-58fbc83ca97b.PNG)

**Comment by hypeJunction** [comment]
Should be fixed.
