### ISSUE TITLE
hypeWall 3.2.3 : Messages posted at 'All Site Activity' redirects the page to the User Wall page

### ISSUE THREAD

**Issue by dranii** [hypeJunction/hypeWall#57]
Default and plain and fresh install of Elgg 1.10.4
hypeWall 3.2.3
hypeFilestore 3.0.0 
Nothing else
Browsers - latest FF, latest Opera

Settings :Select the model for the wall posts: Default Wall functionality

Messages posted at the page All Site Activity goes to the user Wall page
Messages posted at the user Wall page show only the last or latest message

Expected -
Messages posted at the page All Site Activity should show up instantly at the same page.
All previous messages should be seen always.

The previous versions worked correctly.

Thanks for your help in solving this.

**Comment by Daltonmedia** [comment]
Dranii, I had this behaviour before when there was a JS issue.
Check your browserconsole if there is something going on.
You might also want to try this logged in as a user instead of admin. I noticed the 'geolocation' deprication message is bugging some js for hypeWall.

**Comment by hypeJunction** [comment]
For messages to show up instantly, you need hypeLists
