### ISSUE TITLE
WSOD linking to a Sharemaps page (or at least I think so)

### ISSUE THREAD

**Issue by michelesbw** [hypeJunction/hypeWall#58]
Hello Ismayil,
posting a link to a map shared through Share Mapds (https://community.elgg.org/plugins/1086612/releases/1.8.7.1) seems to give WSOD on activity page.
I actually don't remember if i was a direct link like MYSITE/sharemaps/view/515072/sample-map OR the shortened bit.ly URL
Cheers
M

**Comment by gerard-kanters** [comment]
A link that cannot be resolved will result in WSOD. I solved this by editing local hosts file and include the machine

**Comment by michelesbw** [comment]
Thanks Gerard will try that.
Cheers

**Comment by hypeJunction** [comment]
Is this still an issue? Does this happen when you share a link? Or when you share content? If the link, please open an issue with hypeScraper.
