### ISSUE TITLE
WSOD with HypeWall 4.0.1

### ISSUE THREAD

**Issue by michelesbw** [hypeJunction/hypeWall#64]
Hello,
no problems until today but after activating this version I get WSOD on Activity page and in console I see:
GET MYSITE/activity 500 (Internal Server Error)
Navigated to MYSITE/activity
content.js:15 VK. Startup (background is ready)

Also, when I go to Hypewall's settings the system throws the message "hypeWall requires hypeApps" but I have installed it (4.1.2) and tried both to put before alle hype's plugins and after them with no effect.
Same thing with hypescraper 4.1.0
Cheers
M

**Comment by hypeJunction** [comment]
Looks at hypeApps readme to see how to install with composer. I am no
longer including vendor libraries.

**Comment by michelesbw** [comment]
:S sorry
Waaaay too complicated for non-devs then...let's see if I can manage it :)

**Comment by hypeJunction** [comment]
It makes it a lot easier for devs, and since I don't distribute plugins anywhere other than github at this point, there is no reason for me to package each plugin. I might build some sort of installer UI, but not a priority at the moment.
