### ISSUE TITLE
Error deleting wall post

### ISSUE THREAD

**Issue by insideth** [hypeJunction/hypeWall#65]
PHP message: PHP Fatal error:  Call to undefined method hypeJunction\Wall\Post::canDelete() in ...mod/hypeApps/classes/hypeJunction/Controllers/DeleteAction.php on line 33" while reading response header from upstream

I use hypeApps 4.2.4 and hypeWall 4.1.0

**Comment by michelesbw** [comment]
Same here with HypeApps 4.2.11 and HypeWall 4.2.0 with Elgg 1.9.8 (if can be of any help). Cheers

**Comment by hypeJunction** [comment]
Fixed by https://github.com/hypeJunction/hypeApps/commit/2ae28e89b741f588d054a0f4c45d0195c5e94c41
hypeApps 4.2.12 fixes it.
