### ISSUE TITLE
Show post where i'm tagged in

### ISSUE THREAD

**Issue by eugna** [hypeJunction/hypeWall#66]
Hi, I've installed your plugin Hypewall, i've just one problem: on the wall i can only see post i've published, but not post i'm tagged in. I can only see that pushing the button "view all" on the botton of the page. I wish to see each post about me without pushing "view all" button. I use ishouvik_profile plugin for the profile. Thank you.

**Comment by hypeJunction** [comment]
You will need to add additional sql queries to your `elgg_get_river()` as seen here:
https://github.com/hypeJunction/hypeWall/blob/master/views/default/framework/wall/owner.php#L22
