### ISSUE TITLE
Access level not properly saved

### ISSUE THREAD

**Issue by michelesbw** [hypeJunction/hypeWall#67]
Hello,
Elgg 1.9.8, hypewall 4.2, hypeapps 4.2.11. When sving content regardless of the access level selected, only wall's owner and admin can see it. I guess it's always saving content as Private or something alike.

EDIT: also, notifications are sent only to site's admin not also to other friends whose notifications are set ok.

Cheers

**Comment by hypeJunction** [comment]
Are you tagging anyone in the post?

**Comment by michelesbw** [comment]
I am since then using previous versions of wall and related plugins so I don't remember exactly but I am pretty sure I didn't tag anyone, I rarely use tagging people. I have seen the same issue reported on community site by others. Cheers

**Comment by hypeJunction** [comment]
Yeah, found the bug. Pretty dumb.

**Comment by michelesbw** [comment]
:)
