### ISSUE TITLE
 Class 'hypeJunction\Plugin' not found

### ISSUE THREAD

**Issue by nattydreadnatty** [hypeJunction/hypeWall#69]
Hello, after activation HypeWall I got this message:

Fatal error: Class 'hypeJunction\Plugin' not found in /var/www/legtux.org/users/perdurable/www/html/mod/hypeWall/classes/hypeJunction/Wall/Plugin.php on line 16

Elgg version: 1.12

Regards

**Comment by hypeJunction** [comment]
You need to install hypeApps.

**Comment by nattydreadnatty** [comment]
I already did. Versions 4.3.4. Does it have to be before the HypeWall plugin in the plugin list?

**Comment by hypeJunction** [comment]
Did you download the dist version from the Releases tab? 
Yes, before hypeWall just to be safe, but it uses composer autoloader, so it shouldn't matter.

**Comment by nattydreadnatty** [comment]
Yes... I put it after Hyp Apps and now it works. Thanks a lot for your help!
