### ISSUE TITLE
The activity / river stream does not  refresh after submission [Bug report]

### ISSUE THREAD

**Issue by rhisss** [hypeJunction/hypeWall#7]
The activity / river stream does not  refresh after submission  - so it does not show the content just added.

The activity / river stream does not auto refresh - so after hitting submit one has to wonder what has happened. The expected default behavior is the page refreshing (or ajax) to show the stuff just added.

**Comment by jmperu** [comment]
I have the same problem but curl is installed
and I have the latest version of hypewall with all the prerequisites
