### ISSUE TITLE
Group activity and group wall issues

### ISSUE THREAD

**Issue by nattydreadnatty** [hypeJunction/hypeWall#70]
Sorry to disturb you again.

When I try to configure activity widget in my profile, it tells me that there was an issue registering he widget parameters.

Moreover, when I try to access to group walls, I got the message "page not found".

Do you have an idea?

**Comment by hypeJunction** [comment]
Do you use widget manager?

**Comment by nattydreadnatty** [comment]
Well in fact no bcause when I activate it, the widgets of my profil users are all put in the left column of the profile and I can't chang there place... And I'm cannot edit them. I am really sorry it is the first time I use Elgg cms so I am a little bit lost.

**Comment by hypeJunction** [comment]
I need some more info to help you. Anything in server error logs/browser console?

**Comment by nattydreadnatty** [comment]
No I don't see anything.

**Comment by nattydreadnatty** [comment]
Sorry... Found this URL de la requête : 	http://perdurable.legtux.org/html/wall/group/55
Méthode de la requête : 	GET
Code d'état : 	HTTP/1.1 404 Not Found
En-têtes de la requête 22:43:02,000
User-Agent:	Mozilla/5.0 (Windows NT 6.3; rv:42.0) Gecko/20100101 Firefox/42.0
Referer:	http://perdurable.legtux.org/html/groups/profile/55/terre-de-korrigans
Host:	perdurable.legtux.org
Connection:	keep-alive
Accept-Language:	fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding:	gzip, deflate
Accept:	text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Cookie envoyé
Elgg_install:	4f347v8fnsmk4neigrd89pkmi2
Elgg:	98v9kc812g2ejk9v0lf3dvhm40
En-têtes de la réponse Δ1548ms
X-Frame-Options:	SAMEORIGIN
Vary:	User-Agent
Transfer-Encoding:	chunked
Server:	Apache
Pragma:	no-cache
Keep-Alive:	timeout=5, max=100
Expires:	Thu, 19 Nov 1981 08:52:00 GMT
Date:	Fri, 11 Dec 2015 21:42:53 GMT
Content-Type:	text/html; charset=UTF-8
Connection:	Keep-Alive
Cache-Control:	no-store, no-cache, must-revalidate, post-check=0, pre-check=0

**Comment by nattydreadnatty** [comment]
And thi for he activity group widget 

URL de la requête : 	http://perdurable.legtux.org/html/_graphics/ajax_loader_bw.gif
Méthode de la requête : 	GET
Code d'état : 	HTTP/1.1 304 Not Modified
En-têtes de la requête 22:51:18,000
User-Agent:	Mozilla/5.0 (Windows NT 6.3; rv:42.0) Gecko/20100101 Firefox/42.0
Referer:	http://perdurable.legtux.org/html/cache/1449870645/default/css/elgg
If-None-Match:	"a30-5268ab3a21aad"
If-Modified-Since:	Thu, 10 Dec 2015 12:54:04 GMT
Host:	perdurable.legtux.org
Connection:	keep-alive
Cache-Control:	max-age=0
Accept-Language:	fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding:	gzip, deflate
Accept:	image/png,image/*;q=0.8,*/*;q=0.5
Cookie envoyé
Elgg_install:	4f347v8fnsmk4neigrd89pkmi2
Elgg:	98v9kc812g2ejk9v0lf3dvhm40
En-têtes de la réponse Δ59ms
Vary:	User-Agent
Server:	Apache
Keep-Alive:	timeout=5, max=100
Etag:	"a30-5268ab3a21aad"
Date:	Fri, 11 Dec 2015 21:51:09 GMT
Connection:	Keep-Alive

**Comment by nattydreadnatty** [comment]
I installed the widget manager 5.1 version and the isuue with widgets in th profile is now resolved. I am reinstalling every plugin one by one to se if others problems are solved.

**Comment by nattydreadnatty** [comment]
Ok. Problem resolved by widget manager 5.1. Sorry for the disturb. I will tell you if by activating others plugins the issue show up again.

**Comment by nattydreadnatty** [comment]
Well there is still th e group wall issue
