### ISSUE TITLE
Since 4.4 updates don't get pushed to the river

### ISSUE THREAD

**Issue by Daltonmedia** [hypeJunction/hypeWall#71]
Since the 4.4.x releases (everything up as well) the wall doens't get updated by ajax (with hypelists) on a status post. Rolling back to the latest 4.3.x and it's fine again. (This is all also the case with the latest hypelists release)

**Comment by hypeJunction** [comment]
I am quite sure it does.

**Comment by Daltonmedia** [comment]
Ok, would be another conflict then. Just thought it had to do with 4.4 because the only thing I have to do to fix the issue is change the composer required number to anything before 4.4.

Thanks. I'll close it for now

**Comment by hypeJunction** [comment]
Did you update to latest hypeLists?

**Comment by Daltonmedia** [comment]
jep

**Comment by Velody** [comment]
Here too.

**Comment by hypeJunction** [comment]
So, river will only update if you river list is ajaxified with hypeLists (either through global setting, or by adding pagination_type to it).

**Comment by Daltonmedia** [comment]
I'm guessing the problem with my install was that it was a fresh devcopy and there weren't enough riveritems yet to initiate hypelist (no pagination required yet) Sorry, I've only came to this insight by looking at your fix, (which works well).

**Comment by hypeJunction** [comment]
hypeList actually works even with empty lists now. You can see how an empty wall gets updated with a post.

**Comment by Daltonmedia** [comment]
yep, saw it, thanks.
