### ISSUE TITLE
Avatar not focussed in the middle

### ISSUE THREAD

**Issue by gerard-kanters** [hypeJunction/hypeWall#73]
In mobile view with aalborg_theme the avatar is not shown correctly. This happens in both elgg 1.12 and 2.0.3. See below picture what I mean.

![capture](https://cloud.githubusercontent.com/assets/4699801/13651250/d45d5528-e646-11e5-9f6a-7853db855202.PNG)

**Comment by hypeJunction** [comment]
It's your theme. Try setting max-width: 100% on .elgg-avatar img

**Comment by gerard-kanters** [comment]
Nope, that does not work. Fyi, it is not my theme. It is part of core.

**Comment by hypeJunction** [comment]
Can you add this plugin and see if it fixes it: https://github.com/hypeJunction/Elgg-ui_icons/releases
I am sure it's the CSS, don't have time to dig into it at the moment.

**Comment by hypeJunction** [comment]
I can't ensure compatibility with all plugins that mess with user icons. Please modify your own css.
