### ISSUE TITLE
rss feeds are not working, not generated

### ISSUE THREAD

**Issue by michelesbw** [hypeJunction/hypeWall#76]
Users walls' rss feeds (ie /wall/owner/USER?view=rss) are blank and activity page's gives a 500 internal server error.
Elgg 2.1.1 and Hypewall 4.4.7

**Comment by hypeJunction** [comment]
There was never RSS support for the wall - so whatever the core is doing would be responsible for whatever is rendered. It would help if you could see what's in your error logs.
In general, RSS makes little sense for an access controlled feed.
