### ISSUE TITLE
Web services / REST

### ISSUE THREAD

**Issue by DanteSingleton** [hypeJunction/hypeWall#77]
I'm currently tasked with exposing this via ws plugin. Is there native support for this ? and if not may I ask for sample code for a simple post ?

Much appreciated,

-Dante

**Comment by hypeJunction** [comment]
You can just create a new object like you would with any other subtype. Just check the SavePost action class for metadata names.

**Comment by DanteSingleton** [comment]
I have completed this. Thanks for your advice, It was very useful.

-Dante
