### ISSUE TITLE
Pulling all wall posts with comments by user

### ISSUE THREAD

**Issue by DanteSingleton** [hypeJunction/hypeWall#78]
I previously inquired about saving comments. This was hasty as i didn't look though the code thorough enough. In this case due to my inexperience with elgg and this plugin I cannot figure out how to pull posts with comments by user, this is one of the last parts i need to wrap this up. I'm sure this is quite simple, but beyond the scope of my knowledge. If possible can i get a snippet or gist ? My apologies for asking for so much, deadlines lol.

Thank you,

-Dante

**Comment by hypeJunction** [comment]
Do you mean you want to list wall posts that have received comments by a specific user? Something along these lines:

```php
$dbprefix = elgg_get_config('dbprefix');
$comment_subtype_id = (int) get_subtype_id('object', 'comment');
$comment_poster_guid = (int) elgg_get_logged_in_user_guid();
var_dump(elgg_get_entities([
   'types' => 'object',
   'subtypes' => 'hjwall', // or whatever the subtype is
   'wheres' => [
       "EXISTS (SELECT 1 FROM {$dbprefix}entities
		   WHERE type='object' AND subtype=$comment_subtype_id
			   AND container_guid = e.guid AND owner_guid=$comment_poster_guid)"
   ],
]));
```
