### ISSUE TITLE
[widget] seems not honouring the default posts to retrieve

### ISSUE THREAD

**Issue by feroda** [hypeJunction/hypeWall#80]
Hi @hypeJunction !,

with SBW we are experience timeouts due the Dashdoard page. While debugging we noticed slowness added by the hypeWall widget. So I tried to add the widget in my own dashboard and even if the default value in settings is to retrieve 4 posts, it retrieved 23 (that could be all my posts in the wall, I have not checked).

So I switched the value to 1 and I got 1 post. I then switched the value to 4 again and I got 4 posts.

That's why I think the plugin it is not honouring the default value of 4 posts in SBW.

Hope this help, and it will be useful if you have a workaround even the issue is not fixed soon.
Happy hacking
fero

**Comment by hypeJunction** [comment]
I checked the code and added a new widget. The default limit of 4 was set. Something must be odd on your end. Any plugins overwriting the views? 
Try dumping options from lists/wall to see what's happening there.

**Comment by hypeJunction** [comment]
Reopen if still persists.
