### ISSUE TITLE
Private access fails for posts

### ISSUE THREAD

**Issue by joalbor1** [hypeJunction/hypeWall#83]
I am using the hypeWall plugin (4.4.8 version) in my Elgg installation (2.2.1 version). The plugin works fine but (with the wall_friends_tag property enabled) if I want publish a private post in my Wall with an empty tag (no tagged), the 'access_id' value changes from ACCESS_PRIVATE to ACCESS_LOGGED_IN.

**Comment by hypeJunction** [comment]
The access never changes to logged in. If you have tagged friends, there will be a new access collection created.

**Comment by joalbor1** [comment]
Please try to create a private publication with hypeWall without labeling any user. The publication is kept public.

**Comment by joalbor1** [comment]
The error is in line [SavePost#178](https://github.com/hypeJunction/hypeWall/blob/master/classes/hypeJunction/Wall/Actions/SavePost.php#L178), this function does not create a collection of friends but always returns the value 1.

If we look at the class that should create the collection of friends [AccessCollection](https://github.com/hypeJunction/hypeWall/blob/master/classes/hypeJunction/Wall/AccessCollection.php), we can see that the only thing that happens is that AccessCollection object is created but the collection is never saved in the database. 'createCollection' function is never called.

**Comment by hypeJunction** [comment]
Should be fixed now.
