### ISSUE TITLE
when entering website link hypewall get distorted

### ISSUE THREAD

**Issue by merilturock** [hypeJunction/hypeWall#84]
Dear Ismail,
          I recently installed the latest hypewall in elgg 2.2.2 when i try to enter a link & try to post the hypewall distorted the entire page attached image for your reference.

![cg error](https://cloud.githubusercontent.com/assets/1689530/19621701/2c0b0290-98b5-11e6-8e48-315773d6ea1a.PNG)

Thanking you
Meril

**Comment by hypeJunction** [comment]
Use release tags for hypeScraper. Don't use master.
