### ISSUE TITLE
thewire no longer integrates with Hypewall

### ISSUE THREAD

**Issue by DaveONchE** [hypeJunction/hypeWall#85]
The Wire posting from HypeWall does not work even after setting the option in admin settings.

**Comment by hypeJunction** [comment]
I will dropping the wire integration completely in the next major. Too much overhead with no gain and I can't stand the wire. It should still be working but if it doesn't I am not going to spend time fixing it. Feel free to make a PR with a fix.

**Comment by hypeJunction** [comment]
Wire support has been thrown out. I don't want to deal with the wire anymore.
