### ISSUE TITLE
adding a URL requires a protocol, but the tooltip does not explain this & cannot be edited

### ISSUE THREAD

**Issue by propertunist** [hypeJunction/hypeWall#86]
if i type www.google.com in the url input field on the activity page as i try to add a link to my wall - after clicking 'send' i see a popup text box that reads: "please enter a URL".
the only way i can get the url to save is by adding a protocol to the URL such as 'https'.
this is confusing to unskilled users as they are experienced with the well known sites that generally do not require protocols to be added to urls and the tooltip does not explain that the protocol must be added.
additionally, the text for the tooltip is not in the language string list for the plugin, so it will only be in english and i cannot improve it in any way via the usual methods.

i think that ideally there would be no requirement for a protocol to be added and when one isn't added, the default should be https, with a fallback to http if https doesn't work.

**Comment by hypeJunction** [comment]
It's browser behavior for url input type. Change it to text if it bothers you.

**Comment by hypeJunction** [comment]
I don't want to be second guessing protocols.

**Comment by propertunist** [comment]
oh ok, i hadn't seen that before
