### ISSUE TITLE
[feedback] Remove empty space and add ckeditor toggle

### ISSUE THREAD

**Issue by michelesbw** [hypeJunction/hypeWall#87]
Hello,
I have received few feedbacks on which I actually agree so here they are for you to evaluate :)
1 - Remove the empty space highlighted in the screenshot by widening the ckeditor
![screenshot-socialbusinessworld org 2017-01-07 10-46-31](https://cloud.githubusercontent.com/assets/5203511/21741401/a280b7e8-d4d4-11e6-9813-20ceb2a3cb72.png)

2 -Users would like to have plain text as default but also a toggle to enable ckeditor if/when needed (just like hypeinbox messages)
Cheers

**Comment by hypeJunction** [comment]
1. Just do it in your theme. I want to get rid of the image altogether in the next release
2. Should be possible in Elgg 2.3. I am going to remove the option of having wysiwyg enabled by default in the next release.

**Comment by michelesbw** [comment]
As for point 1 I think wall is complete with user avatar as it is now (just needs to be re-positioned to use the whole width for editor) because users may have >1 account and clearly showing which one is in use is important imo.

**Comment by hypeJunction** [comment]
Plaintext input only takes 3-4 rows and it's positioned just fine and looks neat. You chose to use that horrible wysiwyg mammoth, so not my problem 😛

**Comment by michelesbw** [comment]
:D yes of course my problem, just highlighting a possible additiona setting (feedback) :)

**Comment by hypeJunction** [comment]
I have thrown out CKEditor from wall completely. You can add it in your theme if you really want to. I want to keep the wall clean, and the mammoth CKEditor doesn't belong there, neither does HTML.
