### ISSUE TITLE
Some wall posts (example below) cause /activity page not to load

### ISSUE THREAD

**Issue by michelesbw** [hypeJunction/hypeWall#88]
Case: user shared this link via wall post http://www.newseconomy.it/index.php?option=com_k2&view=item&id=625%3Aecco-che-cosa-si-nasconde-dietro-l-aumento-del-pil-calabrese&Itemid=465 and  also selected "Save this link to my bookmarks".
The bookmark was successfully created but the wall item and /activity page could not be loaded anymore, after many secs 524 timeout (as admin I had to delete this post to have it back). Access "Public".
Elgg 2.3 and hypewall 4.4.11
Cheers

**Comment by hypeJunction** [comment]
I suspect it's caused by https://github.com/hypeJunction/hypeScraper/issues/41

**Comment by hypeJunction** [comment]
It was  a different issue, but will be fixed in the next scraper.
