### ISSUE TITLE
Friends tagging not working?

### ISSUE THREAD

**Issue by YanweiJiang** [hypeJunction/hypeWall#89]
I tried to use @ as to tag a friend on the site, but there is not a dropdown list to choose and the tagging is not working. I am using elgg 2.3 and also disabled thewire_tools. thanks

**Comment by hypeJunction** [comment]
There is no mentions dropdown

**Comment by YanweiJiang** [comment]
Will you consider this as an enhancement to have a dropdown list when user typing in the near future?

**Comment by hypeJunction** [comment]
You can use the mentions plugin. I am not planning to duplicate that functionality

**Comment by YanweiJiang** [comment]
cool. thanks
