### ISSUE TITLE
Status action requires a description

### ISSUE THREAD

**Issue by Daltonmedia** [hypeJunction/hypeWall#91]
The status action requires a description and there is none giving with a normal status update on the wall, so it results in a error message that the message is empty

`if (empty($description) && empty($address) && empty($attachment_guids) && empty($upload_guids)) {
	return elgg_error_response(elgg_echo('wall:error:empty_form'));
}`

should this be wrapped in `if ($attachment_guids) {...` perhaps?

e: 2.3.1 hypewall 5.0.1

**Comment by hypeJunction** [comment]
Not sure what you mean. Type in your status and post.

**Comment by Daltonmedia** [comment]
Sorry, I didn't explain myself very well, the title was meant as a fact and not as a suggestion.
I mean that, if I do that I get an elgg error notice saying that I didn't typed anything (Please tell us what's on your mind or add a link first) while I most certainly typed something.

When I look in the action file to see what that message would trigger, I can see that the actionfile requires a 'not empty' description for it to post the status, and since there is no description posted by the form, no wallpost is being made and the user gets the error.

If if change the action, so that a description is not necessary, the wallpost goes through just fine.

**Comment by hypeJunction** [comment]
There is a description field in the form.

**Comment by hypeJunction** [comment]
Ah, you are right, it's called status
