### ISSUE TITLE
[feedback] - Not working with hypewall_extended and toggles

### ISSUE THREAD

**Issue by michelesbw** [hypeJunction/hypeWall#92]
Hello :)
We tested and unfortunately few layout issues arise with hypewall extended.
IMO all functionalities are ok but as for UX, the icons should not disappear when clicked, they should work as toggles so not to only open fields (ie. tags) but also close them. Cheers

![hypewall-extended](https://cloud.githubusercontent.com/assets/5203511/23698048/656ba148-03ea-11e7-81d9-d37914181f69.png)

**Comment by hypeJunction** [comment]
It's a breaking release, so other plugins should adjust. There is nothing I can do in this plugin

**Comment by michelesbw** [comment]
I know, just a feedback since you recommend that plugin in Readme file ;)
I also added the icon toggling thing, feedback :)

**Comment by hypeJunction** [comment]
I have no idea how users are going to interact after it has been displayed. Closing/hiding a field would also mean removing any content that has been added therein, which will cause all kinds of issues with uploaded files etc., so not happening for now.
