### ISSUE TITLE
Hypewall Photo icon

### ISSUE THREAD

**Issue by rayhill75** [hypeJunction/hypeWall#93]
Hi. Great plugin! Running it on Elgg 2.3. All well, except there is NO image upload icon? Any ideas?
![activity](https://cloud.githubusercontent.com/assets/26484231/24043491/bf0c9c86-0b0e-11e7-8776-72b7e4f8e99b.png)

**Comment by hypeJunction** [comment]
Do you have hypeDropzone installed?

**Comment by rayhill75** [comment]
Hi. Yes have drop zone installed

**Comment by hypeJunction** [comment]
Did you enable photos in settings?

**Comment by rayhill75** [comment]
enabled in tidypics plugin. Users have been creating albums and profile pics

**Comment by hypeJunction** [comment]
I don't know what tidypics plugin has to do with this. Did you enable photos in hypeWall settings?

**Comment by rayhill75** [comment]
thats the only place i have any photo settings. Image of my hypewall settings
![hypewall](https://cloud.githubusercontent.com/assets/26484231/24047501/d6a0d1be-0b1d-11e7-95ab-f31ec92e3d13.png)

**Comment by hypeJunction** [comment]
Oh, just checked the code. You need to enable hypeAttachments as well.

**Comment by rayhill75** [comment]
Will download & try it. Do Hype have a profile cover photo plugin?

**Comment by hypeJunction** [comment]
You can take a look at hypeIcons here on github.
