### ISSUE TITLE
Photo upload

### ISSUE THREAD

**Issue by rayhill75** [hypeJunction/hypeWall#94]
Hi.

Spoken to you previously about having issues with photo upload on the activity. On click nothing happens. You said it was a cache or js fault. I cannot find a thing! If i give you my cpanel & elgg site login could you take a look please? In your own time of course, no rush. Thanks in advance

**Comment by hypeJunction** [comment]
Sorry, I don't have time to assist with individual cases. If you find a bug, please report.
