### ISSUE TITLE
"Find Me" doesn't work

### ISSUE THREAD

**Issue by javery86** [hypeJunction/hypeWall#99]
Whenever I click on the "Find Me" link to autopopulate my location, nothing seems to happen. Also, when I inspected it via Google Chrome Console, I see these errors:

container.js:3 [Deprecation] getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
findMe @ container.js:3
dispatch @ jquery.js:2
r.handle @ jquery.js:2

jquery.js:2 Uncaught Error: Syntax error, unrecognized expression: #
    at Function.fa.error (jquery.js:2)
    at fa.tokenize (jquery.js:2)
    at Function.fa [as find] (jquery.js:2)
    at n.fn.init.find (jquery.js:2)
    at HTMLAnchorElement.<anonymous> (tabs.js:3)
    at HTMLDocument.dispatch (jquery.js:2)
    at HTMLDocument.r.handle (jquery.js:2)
fa.error @ jquery.js:2
fa.tokenize @ jquery.js:2
fa @ jquery.js:2
find @ jquery.js:2
(anonymous) @ tabs.js:3
dispatch @ jquery.js:2
r.handle @ jquery.js:2

**Comment by hypeJunction** [comment]
Your site has to be served via https for it to work

**Comment by javery86** [comment]
Actually the SSL was just installed a few moments ago, and it still doesn't work.

**Comment by hypeJunction** [comment]
What's the error?

**Comment by javery86** [comment]
@hypeJunction Please visit https://www.profndoc.com to see what I'm talking about.

**Comment by hypeJunction** [comment]
I don't visit individual websites to check for errors, sorry, enough on my plate. Disable all other non-core plugins and eliminate the problem with another plugin. It looks like you have another unrelated issue.

**Comment by javery86** [comment]
Oh, I figured it out! It was the AjaxTabs plugin from your company that was causing it. Is there any way to modify that plugin so that both can work together?

**Comment by hypeJunction** [comment]
Ajax tabs have become part of Elgg core, so you don't need the plugin.
